Revert "update pipeline"
This reverts commit 1fae1f8e9bc733d1131ac804c32e22ea271bf417.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,42 +18,42 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    # - name: Setup .NET
-    #   uses: actions/setup-dotnet@v2
-    #   with:
-    #     dotnet-version: |
-    #       3.1.x
-    #       6.0.x
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v2
+      with:
+        dotnet-version: |
+          3.1.x
+          6.0.x
 
-    # - name: Restore dependencies
-    #   run: dotnet restore
+    - name: Restore dependencies
+      run: dotnet restore
 
-    # - name: Build
-    #   run: dotnet build --no-restore
+    - name: Build
+      run: dotnet build --no-restore
 
-    # - name: Run unit tests
-    #   run: dotnet test tests/unit/Laserfiche.Repository.Api.Client.Test.csproj --no-build --verbosity normal --logger "trx;LogFileName=unit-test-results.trx"
+    - name: Run unit tests
+      run: dotnet test tests/unit/Laserfiche.Repository.Api.Client.Test.csproj --no-build --verbosity normal --logger "trx;LogFileName=unit-test-results.trx"
 
-    # - name: Run integration tests
-    #   env:
-    #     ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
-    #     SERVICE_PRINCIPAL_KEY:  ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
-    #     REPOSITORY_ID:  ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_3 }}
-    #     AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
-    #     TEST_HEADER: ${{ secrets.TEST_HEADER }}
-    #   run:
-    #     dotnet test tests/integration/Laserfiche.Repository.Api.Client.IntegrationTest.csproj --no-build --verbosity normal --logger "trx;LogFileName=integration-test-results.trx"
+    - name: Run integration tests
+      env:
+        ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
+        SERVICE_PRINCIPAL_KEY:  ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
+        REPOSITORY_ID:  ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_3 }}
+        AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
+        TEST_HEADER: ${{ secrets.TEST_HEADER }}
+      run:
+        dotnet test tests/integration/Laserfiche.Repository.Api.Client.IntegrationTest.csproj --no-build --verbosity normal --logger "trx;LogFileName=integration-test-results.trx"
 
-    # - name: Test Report
-    #   uses: dorny/test-reporter@v1
-    #   if: success() || failure()    # run this step even if previous step failed
-    #   with:
-    #     name: Test Results
-    #     path: '**/*.trx'
-    #     reporter: dotnet-trx
-    #     only-summary: 'false'
-    #     list-tests: 'failed'
-    #     fail-on-error: 'false'
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Test Results
+        path: '**/*.trx'
+        reporter: dotnet-trx
+        only-summary: 'false'
+        list-tests: 'failed'
+        fail-on-error: 'false'
 
   build-documentation:
     runs-on: ubuntu-latest
@@ -62,35 +62,44 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Install dependencies
+    - name: Install doxygen
+      run: sudo apt-get install doxygen
+
+    - name: Check doxygen version
+      run: doxygen --version
+
+    - name: Create temporary directory
+      run: mkdir -p ./docs_temp/${{ github.ref_name }}
+
+    - name: Generate doxygen config
+      run: doxygen -g doxygen.conf
+
+    - name: Rewrite doxygen config
       run: |
-        sudo apt-get update
-        sudo apt list -a doxygen
-        sudo apt-get install doxygen
-        sudo apt-get install graphviz
+        sed -i 's|"My Project"|${{ github.event.repository.name }}|i' doxygen.conf
+        sed -i 's|PROJECT_LOGO           =|PROJECT_LOGO           = logo.png|i' doxygen.conf
+        sed -i 's|EXCLUDE                =|EXCLUDE                = ./tests|i' doxygen.conf
+        sed -i "s|OUTPUT_DIRECTORY       =|OUTPUT_DIRECTORY       = ./docs_temp/${{ github.ref_name }}/|i" doxygen.conf
+        sed -i 's|RECURSIVE              = NO|RECURSIVE              = YES|i' doxygen.conf
+        sed -i 's|GENERATE_LATEX         = YES|GENERATE_LATEX         = NO|i' doxygen.conf
 
-    - name: Check dependency versions
-      run: |
-        doxygen --version
-        dot -V
+    - name: Dump doxygen.conf to check rewrite
+      run: head -n 200 doxygen.conf
 
-    # - name: Create temporary directory
-    #   run: mkdir -p ./docs_temp/
+    - name: Generate doxygen docs
+      run: doxygen doxygen.conf
 
-    # - name: Generate doxygen docs
-    #   run: doxygen doxygen.conf
+    - name: Upload a Build Artifact
+      uses: actions/upload-artifact@v3.1.0
+      with:
+        name: documentation-artifact
+        path: ${{ github.workspace }}/docs_temp/${{ github.ref_name }}/html
 
-    # - name: Upload a Build Artifact
-    #   uses: actions/upload-artifact@v3.1.0
-    #   with:
-    #     name: documentation-artifact
-    #     path: ${{ github.workspace }}/docs_temp/html
+    - name: Delete temporary directory
+      run: rm -r ./docs_temp
 
-    # - name: Delete temporary directory
-    #   run: rm -r ./docs_temp
-
-    # - name: Delete doxygen config
-    #   run: rm -f doxygen.conf
+    - name: Delete doxygen config
+      run: rm -f doxygen.conf
 
 
   publish-documentation:
